import type { Metadata } from "next";
import { Geist, Geist_Mono, Jersey_15 } from "next/font/google";
import "./globals.css";
import Button from "@/components/Button(old)";
import Card from "@/components/Card";
import Button2 from "@/components/Button";
import Card2 from "@/components/Card(old)";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const jersey15 = Jersey_15({
  variable: "--font-jersey",
  weight : "400",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} ${jersey15.variable} antialiased`}>
        <Button>Bouton de Manu avec héritage</Button>    
        <Button2>Bouton de Pierre</Button2>    
        <Card><Button2></Button2>/><u>Carte de Manu</u> <br/>Sans fioriture, avec héritage</Card>
        <Card2><u>Carte de Manu</u> <br/>Avec ombrage</Card2>

        {children}
      </body>
    </html>
  );
}
