import styles from '../../app/Assets.module.css';

const cropIcon = {
  asperge: styles.cropAsperge,
  oignonJaune: styles.cropOignonJaune,
  courgette1: styles.cropCourgette1,
  bettes: styles.cropBettes,
  oignonRouge: styles.cropOignonRouge,
  courgette2: styles.cropCourgette2,
  celeri: styles.cropCeleri,
  all: styles.cropAll,
  courgette3: styles.cropCourgette3,
  chouxFleur: styles.cropChouxFleur,
  poireaux: styles.cropPoireaux,
  tomate1: styles.cropTomate1,
  chouxRouge: styles.cropChouxRouge,
  piment: styles.cropPiment,
  tomate2: styles.cropTomate2,
  poivronVert: styles.cropPoivronVert,
  tomate3: styles.cropTomate3,
  laitue: styles.cropLaitue,
  poivronRouge: styles.cropPoivronRouge,
  petitPois: styles.cropPetitPois,
  salade: styles.cropSalade,
  poivronOrange: styles.cropPoivronOrange,
  haricot: styles.cropHaricot,
  poivronJaune: styles.cropPoivronJaune,
  verdure1: styles.cropVerdure1,
  pimentDoux: styles.cropPimentDoux,
  verdure2: styles.cropVerdure2,
  pasteque: styles.cropPasteque,
  verdure3: styles.cropVerdure3,
  courge1: styles.cropCourge1,
  verdure4: styles.cropVerdure4,
  courge2: styles.cropCourge2,
  patate: styles.cropPatate,
  courge3: styles.cropCourge3,
  rutabaga: styles.cropRutabaga,
  courge4: styles.cropCourge4,
  navet: styles.cropNavet,
  courge5: styles.cropCourge5,
  racine4: styles.cropRacine4,
  courge6: styles.cropCourge6,
  vegetable1: styles.cropVegetable1,
  mais: styles.cropMais,
  racine1: styles.cropRacine1,
  verdure5: styles.cropVerdure5,
  carotte: styles.cropCarotte,
  chouxBlanc: styles.cropChouxBlanc,
  panais: styles.cropPanais,
  chouxBruxelle: styles.cropChouxBruxelle,
  radis: styles.cropRadis,
  chouxRomanesco: styles.cropChouxRomanesco,
  betterave: styles.cropBetterave,
  artichaux: styles.cropArtichaux,
  racine2: styles.cropRacine2,
  poireaux2: styles.cropPoireaux2,
  chouxRave: styles.cropChouxRave,
  random1: styles.cropRandom1,
  oignonBlanc: styles.cropOignonBlanc,
  aubergine1: styles.cropAubergine1,
};

export default cropIcon;
