# Utiliser l'image de base officielle de .NET
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS base
WORKDIR /app
EXPOSE 80

# Utiliser l'image SDK pour construire l'application
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src
COPY ["GreenUDB/GreenUDB.csproj", "GreenUDB/"]
COPY ["GreenUApi/GreenUApi.csproj", "GreenUApi/"]
COPY ["Migrations/Migrations.csproj", "Migrations/"]
COPY ["model/model.csproj", "model/"]
COPY ["obj/obj.csproj", "obj/"]
COPY ["Properties/Properties.csproj", "Properties/"]
RUN dotnet restore "GreenUApi/GreenUApi.csproj"
COPY . .
WORKDIR "/src/GreenUApi"
RUN dotnet build "GreenUApi.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "GreenUApi.csproj" -c Release -o /app/publish

# Final stage
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "GreenUApi.dll"]
