import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import "@radix-ui/themes/styles.css";
// import { Theme } from "@radix-ui/themes";
//import "nes.css/css/nes.min.css";
 import "./styles/globals.css";
import Navbar from "../components/Navbar";
import { Toaster } from "sonner";
import  Button  from "@/components/custom/Button";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
     <body >
      <Button>yolo</Button>

        <div className="min-h-screen pt-20 flex flex-col">
          {children}
        </div>

			</body>
    </html>
  );
}
