// <auto-generated />
using System;
using GreenUApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenUApi.Migrations
{
    [DbContext(typeof(GreenUDB))]
    partial class GreenUDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_unicode_ci")
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GreenUApi.Models.BugReport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Where")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("BugReports");
                });

            modelBuilder.Entity("GreenUApi.Models.Contributor", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Admin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<long>("GardenId")
                        .HasColumnType("bigint")
                        .HasColumnName("Garden_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GardenId" }, "fk_Contributor_Garden_id");

                    b.HasIndex(new[] { "UserId" }, "fk_Contributor_User_id");

                    b.ToTable("Contributor", (string)null);
                });

            modelBuilder.Entity("GreenUApi.Models.Crop", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int?>("Distance_plantation")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("Harvesting")
                        .HasColumnType("date");

                    b.Property<string>("Icon")
                        .HasColumnType("longtext");

                    b.Property<long?>("LineId")
                        .HasColumnType("bigint")
                        .HasColumnName("Line_id");

                    b.Property<short?>("NPot")
                        .HasColumnType("smallint");

                    b.Property<long?>("PlantNurseryId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("Planting")
                        .HasColumnType("date");

                    b.Property<float?>("PotSize")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("Sowing")
                        .HasColumnType("date");

                    b.Property<string>("Variety")
                        .HasColumnType("text");

                    b.Property<string>("Vegetable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("PlantNurseryId");

                    b.HasIndex(new[] { "LineId" }, "fk_Crops_Line_id");

                    b.ToTable("Crops");
                });

            modelBuilder.Entity("GreenUApi.Models.Follower", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("FollowerId")
                        .HasColumnType("bigint")
                        .HasColumnName("Follower_id");

                    b.Property<long?>("GardenId")
                        .HasColumnType("bigint")
                        .HasColumnName("Garden_id");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "FollowerId" }, "fk_Follower_Follower_id");

                    b.HasIndex(new[] { "GardenId" }, "fk_Follower_Garden_id");

                    b.HasIndex(new[] { "UserId" }, "fk_Follower_User_id");

                    b.ToTable("Follower", (string)null);
                });

            modelBuilder.Entity("GreenUApi.Models.Garden", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("Admin_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GardenColor")
                        .HasColumnType("longtext");

                    b.Property<double>("Latitude")
                        .HasColumnType("double");

                    b.Property<double>("Length")
                        .HasColumnType("double");

                    b.Property<double>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Privacy")
                        .HasColumnType("int")
                        .HasColumnName("privacy");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<double>("Width")
                        .HasColumnType("double");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("UserId");

                    b.HasIndex(new[] { "AuthorId" }, "fk_Garden_Admin_id");

                    b.ToTable("Garden", (string)null);
                });

            modelBuilder.Entity("GreenUApi.Models.Line", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<long?>("GardenId")
                        .HasColumnType("bigint");

                    b.Property<double?>("Length")
                        .HasColumnType("double");

                    b.Property<long?>("PLantNurseryId")
                        .HasColumnType("bigint");

                    b.Property<long?>("ParcelId")
                        .HasColumnType("bigint")
                        .HasColumnName("Parcel_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("GardenId");

                    b.HasIndex("PLantNurseryId");

                    b.HasIndex(new[] { "ParcelId" }, "fk_Line_Parcel_id");

                    b.ToTable("Line", (string)null);
                });

            modelBuilder.Entity("GreenUApi.Models.Log", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .HasColumnType("text");

                    b.Property<long?>("AuthorId")
                        .HasColumnType("bigint")
                        .HasColumnName("Author_id");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Created_at");

                    b.Property<long?>("CropId")
                        .HasColumnType("bigint")
                        .HasColumnName("Crop_id");

                    b.Property<long?>("GardenId")
                        .HasColumnType("bigint")
                        .HasColumnName("Garden_id");

                    b.Property<long?>("LineId")
                        .HasColumnType("bigint")
                        .HasColumnName("Line_id");

                    b.Property<long?>("ParcelId")
                        .HasColumnType("bigint")
                        .HasColumnName("Parcel_id");

                    b.Property<long?>("PlantNurseryId")
                        .HasColumnType("bigint");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("UserId");

                    b.ToTable("Logs");
                });

            modelBuilder.Entity("GreenUApi.Models.Parcel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<long>("GardenId")
                        .HasColumnType("bigint")
                        .HasColumnName("Garden_id");

                    b.Property<double?>("Length")
                        .HasColumnType("double");

                    b.Property<short?>("NLine")
                        .HasColumnType("smallint")
                        .HasColumnName("N_line");

                    b.Property<double?>("ParcelAngle")
                        .HasColumnType("double");

                    b.Property<double?>("Width")
                        .HasColumnType("double");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GardenId" }, "fk_Parcel_Garden_id");

                    b.ToTable("Parcel", (string)null);
                });

            modelBuilder.Entity("GreenUApi.Models.PlantNursery", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("GardenId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex("GardenId");

                    b.ToTable("PlantNursery", (string)null);
                });

            modelBuilder.Entity("GreenUApi.Models.TagsInterest", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime(6)");

                    b.Property<long?>("GardenId")
                        .HasColumnType("bigint")
                        .HasColumnName("Garden_id");

                    b.Property<string>("Hashtag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("User_id");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "GardenId" }, "fk_Tags_Garden_id");

                    b.HasIndex(new[] { "UserId" }, "fk_Tags_User_id");

                    b.ToTable("Tags_interest", (string)null);
                });

            modelBuilder.Entity("GreenUApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bio")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("Created_at");

                    b.Property<bool>("Deleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .HasColumnType("text");

                    b.Property<string>("Gender")
                        .HasColumnType("text");

                    b.Property<bool?>("IsAdmin")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Is_admin");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.Property<bool>("Newsletter")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("Postal_code");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text")
                        .HasColumnName("Profile_image");

                    b.Property<string>("Salt")
                        .HasColumnType("text");

                    b.Property<byte>("Skill_level")
                        .HasColumnType("tinyint unsigned");

                    b.Property<bool>("Tou")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Username")
                        .HasColumnType("text");

                    b.Property<long>("Xp")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("GreenUApi.Models.Contributor", b =>
                {
                    b.HasOne("GreenUApi.Models.Garden", "Garden")
                        .WithMany("Contributors")
                        .HasForeignKey("GardenId")
                        .IsRequired()
                        .HasConstraintName("fk_Contributor_Garden_id");

                    b.HasOne("GreenUApi.Models.User", "User")
                        .WithMany("Contributors")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("fk_Contributor_User_id");

                    b.Navigation("Garden");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenUApi.Models.Crop", b =>
                {
                    b.HasOne("GreenUApi.Models.Line", "Line")
                        .WithMany("Crops")
                        .HasForeignKey("LineId")
                        .HasConstraintName("fk_Crops_Line_id");

                    b.HasOne("GreenUApi.Models.PlantNursery", "PlantNursery")
                        .WithMany("Crops")
                        .HasForeignKey("PlantNurseryId")
                        .HasConstraintName("fk_Crops_PlantNursery_id");

                    b.Navigation("Line");

                    b.Navigation("PlantNursery");
                });

            modelBuilder.Entity("GreenUApi.Models.Follower", b =>
                {
                    b.HasOne("GreenUApi.Models.Garden", "Garden")
                        .WithMany("Followers")
                        .HasForeignKey("GardenId")
                        .HasConstraintName("fk_Follower_Garden_id");

                    b.HasOne("GreenUApi.Models.User", "User")
                        .WithMany("FollowerUsers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_Follower_User_id");

                    b.Navigation("Garden");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenUApi.Models.Garden", b =>
                {
                    b.HasOne("GreenUApi.Models.User", null)
                        .WithMany("Gardens")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GreenUApi.Models.Line", b =>
                {
                    b.HasOne("GreenUApi.Models.Garden", "Gardens")
                        .WithMany()
                        .HasForeignKey("GardenId");

                    b.HasOne("GreenUApi.Models.PlantNursery", null)
                        .WithMany("Lines")
                        .HasForeignKey("PLantNurseryId");

                    b.HasOne("GreenUApi.Models.Parcel", "Parcel")
                        .WithMany("Lines")
                        .HasForeignKey("ParcelId")
                        .HasConstraintName("fk_Line_Parcel_id");

                    b.Navigation("Gardens");

                    b.Navigation("Parcel");
                });

            modelBuilder.Entity("GreenUApi.Models.Log", b =>
                {
                    b.HasOne("GreenUApi.Models.User", null)
                        .WithMany("Logs")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GreenUApi.Models.Parcel", b =>
                {
                    b.HasOne("GreenUApi.Models.Garden", "Garden")
                        .WithMany("Parcels")
                        .HasForeignKey("GardenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_Parcel_Garden_id");

                    b.Navigation("Garden");
                });

            modelBuilder.Entity("GreenUApi.Models.PlantNursery", b =>
                {
                    b.HasOne("GreenUApi.Models.Garden", "Garden")
                        .WithMany("PlantNurseries")
                        .HasForeignKey("GardenId");

                    b.Navigation("Garden");
                });

            modelBuilder.Entity("GreenUApi.Models.TagsInterest", b =>
                {
                    b.HasOne("GreenUApi.Models.Garden", "Garden")
                        .WithMany("TagsInterests")
                        .HasForeignKey("GardenId")
                        .HasConstraintName("fk_Tags_Garden_id");

                    b.HasOne("GreenUApi.Models.User", "User")
                        .WithMany("TagsInterests")
                        .HasForeignKey("UserId")
                        .HasConstraintName("fk_Tags_User_id");

                    b.Navigation("Garden");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GreenUApi.Models.Garden", b =>
                {
                    b.Navigation("Contributors");

                    b.Navigation("Followers");

                    b.Navigation("Parcels");

                    b.Navigation("PlantNurseries");

                    b.Navigation("TagsInterests");
                });

            modelBuilder.Entity("GreenUApi.Models.Line", b =>
                {
                    b.Navigation("Crops");
                });

            modelBuilder.Entity("GreenUApi.Models.Parcel", b =>
                {
                    b.Navigation("Lines");
                });

            modelBuilder.Entity("GreenUApi.Models.PlantNursery", b =>
                {
                    b.Navigation("Crops");

                    b.Navigation("Lines");
                });

            modelBuilder.Entity("GreenUApi.Models.User", b =>
                {
                    b.Navigation("Contributors");

                    b.Navigation("FollowerUsers");

                    b.Navigation("Gardens");

                    b.Navigation("Logs");

                    b.Navigation("TagsInterests");
                });
#pragma warning restore 612, 618
        }
    }
}
