name: Build and Test Next.js App

on:
  pull_request:
    branches:
      - main
      - frontDev
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install
        working-directory: my-app

      - name: Build Next.js app
        run: npm run build
        working-directory: my-app

      - name: Type check
        run: npx tsc --noEmit
        working-directory: my-app

      - name: Lint
        run: npm run lint
        working-directory: my-app
